# Generated by Django 5.1.7 on 2025-03-15 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveSmallIntegerField()),
                ('stage_date', models.DateField()),
                ('stage_type', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['tour', 'stage_number'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishing_time', models.DurationField()),
                ('ranking', models.PositiveSmallIntegerField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='game.rider')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.stage')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='game.tour'),
        ),
        migrations.CreateModel(
            name='PlayerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.rider')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_selections', to='game.stage')),
            ],
            options={
                'unique_together': {('player', 'stage')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('tour', 'stage_number')},
        ),
    ]
