# Generated by Django 5.1.7 on 2025-04-12 19:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField(default=2025)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('url_reference', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('start_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_participating', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_number'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveSmallIntegerField()),
                ('stage_date', models.DateField()),
                ('departure', models.CharField(max_length=100, null=True)),
                ('arrival', models.CharField(default='Unknown', max_length=100, null=True)),
                ('distance', models.PositiveSmallIntegerField(null=True)),
                ('stage_type', models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Hills', 'Hills'), ('Punch', 'Punch'), ('Mountain', 'Mountain'), ('Mountain climb finish', 'Mountain climb finish'), ('Indiv. Time Trial', 'Indiv. Time Trial'), ('Team TT', 'Team Time Trial')], max_length=30, null=True)),
                ('start_time', models.TimeField(default=datetime.time(12, 0))),
                ('is_canceled', models.BooleanField(default=False)),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='game.race')),
            ],
            options={
                'ordering': ['race', 'stage_number'],
                'unique_together': {('race', 'stage_number')},
            },
        ),
        migrations.CreateModel(
            name='StageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishing_time', models.DurationField(blank=True, null=True)),
                ('ranking', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bonus', models.DurationField(default=datetime.timedelta(0))),
                ('gc_time', models.DurationField(blank=True, null=True)),
                ('gc_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='game.rider')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.stage')),
            ],
        ),
        migrations.AddField(
            model_name='rider',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.team'),
        ),
        migrations.CreateModel(
            name='PlayerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.rider')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_selections', to='game.stage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'stage'), name='unique_stage_selection'), models.UniqueConstraint(condition=models.Q(('stage__isnull', True)), fields=('player',), name='unique_backup_selection')],
            },
        ),
    ]
