# Generated by Django 5.1.7 on 2025-04-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerUciPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uci_points', models.SmallIntegerField(blank=True, null=True)),
                ('gc_rank', models.SmallIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('race_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.raceparticipant')),
            ],
        ),
    ]
