# Generated by Django 5.1.7 on 2025-03-19 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ['start_number']},
        ),
        migrations.AddField(
            model_name='rider',
            name='is_participating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='start_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageresult',
            name='bonus',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='tour',
            name='url_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
