# Generated by Django 5.1.7 on 2025-05-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playerucipoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='has_finished',
            field=models.BooleanField(default=False),
        ),
    ]
