# Generated by Django 5.1.7 on 2025-03-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_rider_options_rider_is_participating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('url_reference', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['race', 'stage_number']},
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stage',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='game.race'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('race', 'stage_number')},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='tour',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
