# Generated by Django 5.1.7 on 2025-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_race_alter_stage_options_alter_stage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
