# Generated by Django 5.1.7 on 2025-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_stage_has_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
