# Generated by Django 5.1.7 on 2025-03-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_stage_stage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='arrival',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='departure',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='distance',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
