# Generated by Django 5.1.7 on 2025-03-30 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_stage_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerselection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Hills', 'Hills'), ('Punch', 'Punch'), ('Mountain', 'Mountain'), ('Mountain climb finish', 'Mountain climb finish'), ('Indiv. Time Trial', 'Indiv. Time Trial'), ('Team TT', 'Team Time Trial')], max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='playerselection',
            constraint=models.UniqueConstraint(fields=('player', 'stage'), name='unique_stage_selection'),
        ),
        migrations.AddConstraint(
            model_name='playerselection',
            constraint=models.UniqueConstraint(condition=models.Q(('stage__isnull', True)), fields=('player',), name='unique_backup_selection'),
        ),
    ]
