# Generated by Django 5.1.7 on 2025-03-30 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_playerselection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerselection',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_selections', to='game.stage'),
        ),
    ]
