# Generated by Django 5.1.7 on 2025-03-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_playerselection_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageresult',
            name='finishing_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
