# Generated by Django 5.1.7 on 2025-04-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_stageresult_finishing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageresult',
            name='gc_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageresult',
            name='gc_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
