# Generated by Django 5.1.7 on 2025-04-03 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_stageresult_gc_rank_stageresult_gc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageresult',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='game.stage'),
        ),
    ]
