# Generated by Django 5.1.7 on 2025-04-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_stageresult_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageresult',
            name='gc_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
