# Generated by Django 5.1.7 on 2025-04-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_stageresult_gc_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
