# Generated by Django 5.1.7 on 2025-04-07 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_stage_is_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageresult',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.stage'),
        ),
    ]
