# Generated by Django 5.1.7 on 2025-04-24 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
        ('game', '0002_playerucipoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='UciPointsAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.race')),
            ],
        ),
    ]
