# Generated by Django 5.1.7 on 2025-04-03 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
        ('game', '0012_alter_stageresult_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etlrun',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.stage'),
        ),
    ]
